update mintegral adapter to 16.6.31
ChartBoost/chartboost-mediation-android-adapter-mintegral pull request #43
Opened 2024-02-12 22:36 UTC by CB-CharleyLiu

update mintegral adapter to 16.6.31

2024-02-12 22:37 UTC, chauduyphanvu requested changes
The README also needs to be updated.

2024-02-12 22:37 UTC, chauduyphanvu commented on CHANGELOG.md
> +### 4.16.6.31.0
Nit: let's have a new line above this

2024-02-12 22:45 UTC, bichenwang approved these changes

2024-02-12 22:45 UTC, chauduyphanvu approved these changes

2024-02-14 20:02 UTC, CB-RyanMcCormick approved these changes

2024-02-27 20:13 UTC, merged